<a href="https://colab.research.google.com/github/dharineeshramtp2000/Logistic-Regression-Fish-Species-Predictor/blob/master/Fish%20species%20Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset. Here we use the dataset from [Kaggle](https://www.kaggle.com/aungpyaeap/fish-market).
![](https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fgrrlscientist%2Ffiles%2F2018%2F09%2Foo_231160-1200x865.jpg)
---
Here the fishes are separated on the basis of their height, length, width, weight(a.k.a independent variables)

So our dependent variable consists of the names of the fish species.




In [0]:
Dataset = pd.read_csv("Fish.csv")
X = Dataset.iloc[ : ,[1,2,3,5,6]].values
y = Dataset.iloc[ : , 0].values


Now lets feature scale our independent variables from our famous [scikit](https://scikit-learn.org/stable/) library

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

Splitting the dataset into training and testing and performing a good shuffle of data

In [0]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X , y , test_size = 0.3, random_state= 42,shuffle= True)

Now lets define our Logistic Regression model.
Here we define Liblinear algorithm based LR with one vs all stratergy.
We can also use other methods like Gradient Descent, LBFGS etc..,
But we stick to Liblinear as it performs well for small data.

Feel free to use the [Documnetaton for Logistic Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000, random_state = 0, multi_class='ovr', solver='lbfgs')
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

Now lets predict with our test set

In [0]:
y_pred = classifier.predict(X_test)

Its time for evaluating our model.
![](https://hatrabbits.com/wp-content/uploads/2018/08/brainstorm-criteria-evaluation.jpg)

---
Lets first predict how our model is fitting for our training set
We use the famous
1.   f1 score
2.   accuracy 
to evaluate the model





In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [40]:
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY ---------------------->",acc_train)
print("F1 SCORE ---------------------->",f1_train)

Traing set results
ACCURACY ----------------------> 0.7747747747747747
F1 SCORE ----------------------> 0.7052162396342622


Now lets see how well is our model. So now lets evaluate with our test set 

In [41]:
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY ---------------------->",acc_test)
print("F1 SCORE ---------------------->",f1_test)

Test set results
ACCURACY ----------------------> 0.8333333333333334
F1 SCORE ----------------------> 0.7833333333333333


Now lets have our famous Confusion Matrix to visually understand.

In [42]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[13  0  0  0  0  0  0]
 [ 0  2  0  0  1  0  0]
 [ 0  0 14  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  0  0  6  0]
 [ 0  0  3  0  0  0  0]]


Our model has worked well with our test set too.
The**accuaracy** and **f1 score** for both test and training set is good.
Its always to put a question and ask to ourselves that is this the best model?

---

Obvisouly not!
We can still achive our accuracy by changing our models, changing the independent variables, change the metrics and so on.
Its great that we have successfully implemented logistic regression with our fish species dataset.